# ce_nodes.py
"""
This file is the definitive manifest for all Conditional Element "Speculation Environments".

Each node is a blueprint for a mini-application, defining its purpose, UI, and data structures.

- `details_schema`: Defines fields for the high-level "Details" view. These are often narrative
  summaries that are excellent targets for "Generate" AI actions.

- `resource_schema`: Defines the structured data for items in the "Resources" collection. This
  drives the Resource Editor form and the rendering of Resource Cards. A variety of `type`
  values can be used to render different UI controls on the frontend.
"""

NODES = {
    "Default": {
        "definition": "A general-purpose workspace for capturing information, notes, and links that don't fit into a more specialized category.",
        "icon": "fa-solid fa-cube",
        "color": "#95a5a6",
        "details_schema": [
            {"name": "summary", "label": "Overall Summary", "type": "textarea", "placeholder": "Provide a high-level summary of the information contained in this element."}
        ],
        "resource_schema": [
            {"key": "title", "label": "Title", "type": "text"},
            {"key": "description", "label": "Description", "type": "textarea"},
            {"key": "url", "label": "Reference URL", "type": "text"},
            {"key": "tags", "label": "Tags", "type": "tags"}
        ]
    },
    "Research": {
        "definition": "A workspace for discovering, analyzing, and synthesizing research materials like papers, articles, and data sources.",
        "icon": "fa-solid fa-flask",
        "color": "#ec407a",
        "details_schema": [
            {"name": "research_question", "label": "Primary Research Question", "type": "textarea", "placeholder": "What is the core question this research aims to answer?"},
            {"name": "executive_summary", "label": "Executive Summary", "type": "textarea", "placeholder": "A high-level synthesis of all curated resources, which can be generated by the Speculate Co-Pilot."}
        ],
        "resource_schema": [
            {"key": "title", "label": "Topic / Paper Title", "type": "text"},
            {"key": "url", "label": "URL", "type": "text"},
            {"key": "snippet", "label": "Snippet / Abstract", "type": "textarea"},
            {"key": "relevance", "label": "Relevance Score", "type": "number", "placeholder": "e.g., 95"},
            {"key": "status", "label": "Status", "type": "select", "options": ["Pending", "Reviewed", "Verified"]},
            {"key": "tags", "label": "Tags", "type": "tags", "placeholder": "e.g., clinical-trial, material-science"}
        ]
    },
    "Risk": {
        "definition": "A workspace for identifying, assessing, and creating mitigation plans for potential risks.",
        "icon": "fa-solid fa-exclamation-triangle",
        "color": "#e53935",
        "details_schema": [
            {"name": "risk_overview", "label": "Risk Management Overview", "type": "textarea", "placeholder": "Describe the overall approach to identifying and mitigating risks for this COS."}
        ],
        "resource_schema": [
            {"key": "risk_title", "label": "Risk Title", "type": "text"},
            {"key": "description", "label": "Description", "type": "textarea", "placeholder": "Describe the cause and effect of this risk."},
            {"key": "likelihood", "label": "Likelihood", "type": "select", "options": ["Low", "Medium", "High", "Very High"]},
            {"key": "impact", "label": "Impact", "type": "select", "options": ["Low", "Medium", "High", "Critical"]},
            {"key": "mitigation_plan", "label": "Mitigation Plan", "type": "textarea"}
        ]
    },
    "Stakeholder": {
        "definition": "A directory for managing information about people, groups, or organizations involved in or affected by the project.",
        "icon": "fa-solid fa-user-friends",
        "color": "#ffca28",
        "details_schema": [
            {"name": "engagement_strategy", "label": "Overall Engagement Strategy", "type": "textarea", "placeholder": "Describe the plan for managing communications with all stakeholders. Use the SSPEC Network to find potential contacts."}
        ],
        "resource_schema": [
            {"key": "name", "label": "Name", "type": "text"},
            {"key": "role", "label": "Role / Organization", "type": "text"},
            {"key": "stance", "label": "Stance", "type": "select", "options": ["Supporter", "Neutral", "Blocker", "Influencer"]},
            {"key": "engagement_level", "label": "Engagement Level", "type": "select", "options": ["Inform", "Consult", "Collaborate"]},
            {"key": "contact_info", "label": "Contact Info", "type": "text"}
        ]
    },
    "Praxis": {
        "definition": "An action-oriented workspace for defining tasks, assigning ownership, and tracking the status of practical work.",
        "icon": "fa-solid fa-tasks",
        "color": "#5c6bc0",
        "details_schema": [
            {"name": "action_plan_overview", "label": "Action Plan Overview", "type": "textarea", "placeholder": "Describe the overall strategy for the tasks listed below. The Co-Pilot can help break this down into specific actions."}
        ],
        "resource_schema": [
            {"key": "task_name", "label": "Action / Task", "type": "text"},
            {"key": "owner", "label": "Owner", "type": "text"},
            {"key": "status", "label": "Status", "type": "select", "options": ["Not Started", "In Progress", "Blocked", "Completed"]},
            {"key": "due_date", "label": "Due Date", "type": "date"},
            {"key": "description", "label": "Description & Acceptance Criteria", "type": "textarea"}
        ]
    },
    "Timeline": {
        "definition": "A workspace for specifying key dates, milestones, and project scheduling.",
        "icon": "fa-solid fa-clock",
        "color": "#ba68c8",
        "details_schema": [
            {"name": "timeline_summary", "label": "Timeline Summary", "type": "textarea", "placeholder": "Describe any key dependencies, critical path items, or overall project duration."}
        ],
        "resource_schema": [
            {"key": "milestone", "label": "Milestone / Event", "type": "text"},
            {"key": "start_date", "label": "Start Date", "type": "date"},
            {"key": "end_date", "label": "End Date", "type": "date"},
            {"key": "notes", "label": "Notes", "type": "textarea"}
        ]
    },
    "Collaboration": {
        "definition": "A directory for managing formal partnerships and joint efforts with external entities.",
        "icon": "fa-solid fa-handshake",
        "color": "#4dd0e1",
        "details_schema": [
            {"name": "collaboration_objective", "label": "Collaboration Objective", "type": "textarea", "placeholder": "What is the primary goal of engaging with these partners? Use the SSPEC Network to find potential collaborators."}
        ],
        "resource_schema": [
            {"key": "partner_name", "label": "Partner Name/Organization", "type": "text"},
            {"key": "area_of_collaboration", "label": "Area of Collaboration", "type": "text"},
            {"key": "status", "label": "Status", "type": "select", "options": ["Prospect", "In Discussion", "Active", "Completed"]},
            {"key": "contact_person", "label": "Primary Contact", "type": "text"}
        ]
    },
    "Policy": {
        "definition": "A workspace for tracking and analyzing internal policies, guidelines, or organizational rules.",
        "icon": "fa-solid fa-gavel",
        "color": "#78909c",
        "details_schema": [
            {"name": "policy_landscape", "label": "Internal Policy Landscape", "type": "textarea", "placeholder": "Describe the overall internal policy environment relevant to this COS."}
        ],
        "resource_schema": [
            {"key": "policy_name", "label": "Policy / Guideline Name", "type": "text"},
            {"key": "governing_dept", "label": "Governing Department", "type": "text"},
            {"key": "implication", "label": "Implication for Project", "type": "textarea"}
        ]
    },
    "Legislation": {
        "definition": "A workspace for tracking and analyzing external legal considerations, regulations, and laws.",
        "icon": "fa-solid fa-balance-scale",
        "color": "#546e7a",
        "details_schema": [
            {"name": "legal_summary", "label": "Legal & Compliance Strategy", "type": "textarea", "placeholder": "Outline the approach to legal and compliance matters."}
        ],
        "resource_schema": [
            {"key": "legal_requirement", "label": "Legal Requirement / Regulation", "type": "text"},
            {"key": "governing_body", "label": "Governing Body (e.g., FDA, EMA)", "type": "text"},
            {"key": "jurisdiction", "label": "Jurisdiction", "type": "text"},
            {"key": "compliance_status", "label": "Compliance Status", "type": "select", "options": ["Compliant", "In Review", "Action Required"]}
        ]
    },
    "Environment": {
        "definition": "A workspace for analyzing physical, systemic, or market environment factors.",
        "icon": "fa-solid fa-leaf",
        "color": "#66bb6a",
        "details_schema": [
            {"name": "sustainability_statement", "label": "Sustainability/Impact Statement", "type": "textarea", "placeholder": "Summarize the project's overall environmental or market impact goals."}
        ],
        "resource_schema": [
            {"key": "factor", "label": "Environmental Factor", "type": "text"},
            {"key": "impact_assessment", "label": "Impact Assessment", "type": "textarea"},
            {"key": "mitigation_strategy", "label": "Mitigation Strategy", "type": "textarea"}
        ]
    },
    "Opportunity": {
        "definition": "A workspace for identifying and planning how to capitalize on potential positive outcomes, innovations, or advantages.",
        "icon": "fa-solid fa-lightbulb",
        "color": "#26c6da",
        "details_schema": [
            {"name": "opportunity_summary", "label": "Opportunity Landscape", "type": "textarea", "placeholder": "Summarize the key opportunities that could be pursued in relation to this COS."}
        ],
        "resource_schema": [
            {"key": "opportunity_title", "label": "Opportunity", "type": "text"},
            {"key": "potential_value", "label": "Potential Value / Upside", "type": "text"},
            {"key": "exploitation_plan", "label": "Exploitation Plan", "type": "textarea"}
        ]
    },
     "Advocacy": {
        "definition": "A workspace for planning and tracking efforts to build support, influence opinion, and secure buy-in.",
        "icon": "fa-solid fa-bullhorn",
        "color": "#ff7043",
        "details_schema": [
            {"name": "campaign_goal", "label": "Primary Campaign Goal", "type": "textarea", "placeholder": "What is the single most important outcome of this advocacy effort?"}
        ],
        "resource_schema": [
            {"key": "initiative_name", "label": "Initiative Name", "type": "text"},
            {"key": "target_audience", "label": "Target Audience", "type": "text"},
            {"key": "key_message", "label": "Key Message", "type": "textarea"},
            {"key": "status", "label": "Status", "type": "select", "options": ["Planning", "Active", "Completed"]}
        ]
    },
    "Resource": {
        "definition": "A workspace for listing and managing the tangible or intangible resources and assets required for the COS.",
        "icon": "fa-solid fa-tools",
        "color": "#8d6e63",
        "details_schema": [
            {"name": "resource_summary", "label": "Resource Allocation Summary", "type": "textarea", "placeholder": "Provide a high-level summary of resource needs, dependencies, and budget considerations."}
        ],
        "resource_schema": [
            {"key": "resource_name", "label": "Resource Name", "type": "text"},
            {"key": "resource_type", "label": "Type", "type": "select", "options": ["Funding", "Personnel", "Equipment", "Software", "Data"]},
            {"key": "quantity", "label": "Quantity/Amount", "type": "text"},
            {"key": "status", "label": "Allocation Status", "type": "select", "options": ["Requested", "Approved", "Allocated"]}
        ]
    }
}

def get_valid_node_types():
    """Returns a list of all valid node type keys."""
    return list(NODES.keys())