domain_icons = {
"Academic Research": "fas fa-graduation-cap",
"Accounting & Auditing": "fas fa-calculator",
"Acrobatics & Gymnastics": "fas fa-user-ninja",
"Advertising & Marketing": "fas fa-bullhorn",
"Aerospace Engineering": "fas fa-space-shuttle",
"Aging & Geriatrics": "fas fa-walking",
"Agriculture & Farming": "fas fa-tractor",
"Alternative Energy Sources": "fas fa-solar-panel",
"Architectural Design": "fas fa-hammer",
"Art & Fine Arts": "fas fa-paint-brush",
"Artificial Intelligence & Machine Learning": "fas fa-robot",
"Astronomy & Space Exploration": "fas fa-star",
"Automotive Engineering & Design": "fas fa-car",
"Aviation & Aircraft": "fas fa-plane",
"Backpacking & Hiking": "fas fa-campground",
"Banking & Financial Services": "fas fa-university",
"Biochemistry & Biophysics": "fas fa-dna",
"Biology & Life Sciences": "fas fa-leaf",
"Biomedical Engineering": "fas fa-syringe",
"Biotechnology & Genetic Engineering": "fas fa-microscope",
"Blockchain Technology": "fas fa-cubes",
"Blogging & Writing": "fas fa-blog",
"Book Clubs & Reading": "fas fa-book",
"Business Management & Administration": "fas fa-briefcase",
"Camping & Outdoor Recreation": "fas fa-campground",
"Cannabis & Hemp": "fas fa-leaf",
"Car Racing & Motorsports": "fas fa-flag-checkered",
"Chemical Engineering & Materials Science": "fas fa-atom",
"Chemicals & Pharmaceuticals": "fas fa-flask",
"Chemistry & Physical Sciences": "fas fa-flask",
"Chess & Board Games": "fas fa-chess-board",
"Civil & Environmental Engineering": "fas fa-city",
"Climate Change & Environmental Issues": "fas fa-leaf",
"Cloud Computing & Networking": "fas fa-cloud",
"Coding & Software Development": "fas fa-laptop-code",
"Cognitive Science & Psychology": "fas fa-brain",
"Collaborative Consumption & Sharing Economy": "fas fa-users-cog",
"Collecting & Hobbies": "fas fa-archive",
"Comedy & Humor": "fas fa-laugh",
"Communications & Media": "fas fa-satellite",
"Computational Linguistics & Natural Language Processing": "fas fa-language",
"Computer Games & Video Games": "fas fa-gamepad",
"Computer Science & Information Technology": "fas fa-laptop-code",
"Construction & Building Trades": "fas fa-wrench",
"Construction Management & Engineering": "fas fa-hard-hat",
"Consulting & Professional Services": "fas fa-briefcase",
"Consumer Goods & Retail": "fas fa-gift",
"Consumer Products & Electronics": "fas fa-shopping-cart",
"Cooking & Culinary Arts": "fas fa-utensils",
"Cosplay & Costume Design": "fas fa-theater-masks",
"Crafts & DIY": "fas fa-cut",
"Creative Writing & Journalism": "fas fa-pen-fancy",
"Criminal Justice": "fas fa-gavel",
"Customer Service": "fas fa-headset",
"Cybersecurity": "fas fa-shield-alt",
"Dancing": "fas fa-drum",
"Data Science": "fas fa-chart-bar",
"Design": "fas fa-pencil-ruler",
"Digital Marketing": "fas fa-globe",
"Distribution": "fas fa-truck-loading",
"Diving": "fas fa-swimmer",
"Dog Training": "fas fa-dog",
"Drawing": "fas fa-pen",
"E-commerce": "fas fa-shopping-cart",
"Ecology": "fas fa-leaf",
"Economic Development": "fas fa-chart-line",
"Economics": "fas fa-chart-line",
"Education": "fas fa-graduation-cap",
"Electrical Engineering": "fas fa-bolt",
"Electronics": "fas fa-microchip",
"Emerging Technology": "fas fa-robot",
"Energy": "fas fa-lightbulb",
"Engineering": "fas fa-cogs",
"Entertainment": "fas fa-film",
"Environmental": "fas fa-leaf",
"Environmental Conservation": "fas fa-recycle",
"Environmental Engineering": "fas fa-recycle",
"Environmental Science": "fas fa-tree",
"Exercise": "fas fa-dumbbell",
"Extreme Sports": "fas fa-dharmachakra",
"Fantasy Sports": "fas fa-trophy",
"Fashion": "fas fa-tshirt",
"Fencing": "fas fa-futbol",
"Film Studies": "fas fa-film",
"Financial Services": "fas fa-money-check-alt",
"Fishing": "fas fa-fish",
"Food": "fas fa-utensils",
"Food Science": "fas fa-utensils",
"Food Service": "fas fa-utensils",
"Forensic Science": "fas fa-microscope",
"Frisbee": "fas fa-flying-disc",
"Gambling": "fas fa-dice",
"Game Development": "fas fa-gamepad",
"Gaming": "fas fa-gamepad",
"Gardening": "fas fa-leaf",
"Gender Equality": "fas fa-venus-mars",
"Genealogy": "fas fa-dna",
"Geography": "fas fa-globe-americas",
"Geology": "fas fa-mountain",
"Global Health": "fas fa-globe",
"Graphic Design": "fas fa-palette",
"Guitar": "fas fa-guitar",
"Handball": "fas fa-futbol",
"Handwriting Analysis": "fas fa-pen",
"Healthcare": "fas fa-medkit",
"Hiking": "fas fa-hiking",
"History": "fas fa-landmark",
"Hockey": "fas fa-hockey-puck",
"Home Improvement": "fas fa-hammer",
"Horror": "fas fa-ghost",
"Hospitality": "fas fa-concierge-bell",
"Human Resources": "fas fa-users-cog",
"Human Rights": "fas fa-people-carry",
"Humanitarian Aid": "fas fa-hands-helping",
"Hunting": "fas fa-crosshairs",
"Hydroponics": "fas fa-leaf",
"Illustration": "fas fa-pen-nib",
"Immunology": "fas fa-syringe",
"Industrial Design": "fas fa-industry",
"Information Technology": "fas fa-laptop-code",
"Insurance": "fas fa-shield-alt",
"Interior Design": "fas fa-paint-roller",
"International Relations": "fas fa-globe",
"Internet": "fas fa-globe",
"Investing": "fas fa-chart-pie",
"Jewelry": "fas fa-gem",
"Journalism": "fas fa-newspaper",
"Juggling": "fas fa-jedi",
"Kayaking": "fas fa-water",
"Knitting": "fas fa-crochet",
"Language Learning": "fas fa-language",
"Law": "fas fa-balance-scale",
"Leadership": "fas fa-user-tie",
"Leisure": "fas fa-cocktail",
"Library Science": "fas fa-book",
"Literature": "fas fa-book-open",
"Logistics": "fas fa-truck",
"Machine Learning": "fas fa-brain",
"Magic": "fas fa-hat-wizard",
"Management": "fas fa-tasks",
"Manufacturing": "fas fa-industry",
"Marine Biology": "fas fa-fish",
"Marketing": "fas fa-bullhorn",
"Martial Arts": "fas fa-fist-raised",
"Materials Science": "fas fa-cube",
"Mathematics": "fas fa-calculator",
"Mechanical Engineering": "fas fa-cogs",
"Media": "fas fa-tv",
"Medical Research": "fas fa-microscope",
"Medicine": "fas fa-stethoscope",
"Meditation & Mindfulness": "fas fa-om",
"Metallurgy": "fas fa-cog",
"Meteorology": "fas fa-cloud-sun",
"Microbiology": "fas fa-bacteria",
"Mineralogy": "fas fa-gem",
"Mining": "fas fa-hard-hat",
"Motorcycling": "fas fa-motorcycle",
"Mountain Biking": "fas fa-biking",
"Movies & Film": "fas fa-film",
"Music": "fas fa-music",
"Music Production": "fas fa-headphones",
"Musical Instruments": "fas fa-guitar",
"Musical Theater": "fas fa-theater-masks",
"Neuroscience": "fas fa-brain",
"Nonprofit": "fas fa-hands-helping",
"Nutrition":"fas fa-apple-alt",
"Oceanography": "fas fa-water",
"Oil & Gas": "fas fa-gas-pump",
"Online Learning": "fas fa-laptop",
"Optics & Photonics": "fas fa-lightbulb",
"Organic Chemistry": "fas fa-leaf",
"Outdoor Activities": "fas fa-sun",
"Painting": "fas fa-paint-brush",
"Paranormal": "fas fa-ghost",
"Parenting": "fas fa-baby",
"Performing Arts": "fas fa-theater-masks",
"Personal Finance": "fas fa-wallet",
"Pet Care": "fas fa-paw",
"Pharmaceuticals": "fas fa-pills",
"Philanthropy": "fas fa-hand-holding-heart",
"Philosophy": "fas fa-lightbulb",
"Photography": "fas fa-camera",
"Physical Fitness": "fas fa-dumbbell",
"Physics": "fas fa-atom",
"Physiology": "fas fa-heartbeat",
"Plant Science": "fas fa-leaf",
"Plumbing": "fas fa-wrench",
"Podcasting": "fas fa-microphone",
"Poetry": "fas fa-feather-alt",
"Political Science": "fas fa-vote-yea",
"Politics": "fas fa-landmark",
"Pottery": "fas fa-vase",
"Programming": "fas fa-code",
"Project Management": "fas fa-tasks",
"Psychology": "fas fa-brain",
"Public Health": "fas fa-heartbeat",
"Public Relations": "fas fa-bullhorn",
"Public Speaking": "fas fa-microphone",
"Publishing": "fas fa-book",
"Quantum Physics": "fas fa-atom",
"Real Estate": "fas fa-home",
"Recreational Sports": "fas fa-basketball-ball",
"Religion & Spirituality": "fas fa-pray",
"Renewable Energy": "fas fa-wind",
"Research": "fas fa-search",
"Robotics": "fas fa-robot",
"Running": "fas fa-running",
"Sailing": "fas fa-anchor",
"Sales": "fas fa-handshake",
"Science": "fas fa-flask",
"Science Fiction": "fas fa-rocket",
"Screenwriting": "fas fa-film",
"Sculpture": "fas fa-splotch",
"Security": "fas fa-shield-alt",
"Sewing": "fas fa-cut",
"Skateboarding": "fas fa-skating",
"Skiing": "fas fa-skiing",
"Small Business": "fas fa-store",
"Social Media": "fas fa-hashtag",
"Social Science": "fas fa-users",
"Software Development": "fas fa-code",
"Space": "fas fa-rocket",
"Sports": "fas fa-football-ball",
"Statistics": "fas fa-chart-bar",
"Stock Market": "fas fa-chart-line",
"Strategy": "fas fa-chess",
"Surfing": "fas fa-surf",
"Sustainability": "fas fa-leaf",
"Swimming": "fas fa-swimmer",
"Table Tennis": "fas fa-table-tennis",
"Teaching": "fas fa-chalkboard-teacher",
"Technology": "fas fa-microchip",
"Telecommunications": "fas fa-phone",
"Television": "fas fa-tv",
"Tennis": "fas fa-tennis-ball",
"Theater": "fas fa-theater-masks",
"Tourism": "fas fa-plane",
"Travel": "fas fa-globe",
"Urban Planning": "fas fa-city",
"Veterinary Medicine": "fas fa-paw",
"Video Production": "fas fa-video",
"Virtual Reality": "fas fa-vr-cardboard",
"Visual Arts": "fas fa-palette",
"Viticulture": "fas fa-wine-glass",
"Volleyball": "fas fa-volleyball-ball",
"Water Sports": "fas fa-swimmer",
"Web Design": "fas fa-laptop-code",
"Web Development": "fas fa-code",
"Weightlifting": "fas fa-dumbbell",
"Wildlife Conservation": "fas fa-frog",
"Woodworking": "fas fa-hammer",
"Writing": "fas fa-pen",
"Yoga": "fas fa-spa",
"Zoology": "fas fa-paw"
}