"""Switch to UUID primary keys

Revision ID: 1948db49ac7f
Revises: 
Create Date: 2024-01-08 19:18:58.033637

"""
from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision = '1948db49ac7f'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():  
    # ### commands auto generated by Alembic - please adjust! ###  
      
    # Drop the foreign key constraint to prevent issues while altering the column type  
    op.drop_constraint('ce_cos_id_fkey', 'ce', type_='foreignkey')  
  
    # Drop the default value from the 'id' column of 'cos' table  
    op.alter_column('cos', 'id', existing_type=sa.INTEGER(), server_default=None)  
  
    # Change the 'id' column type to UUID  
    op.execute('ALTER TABLE cos ALTER COLUMN id TYPE UUID USING id::text::uuid')  
  
    # Change the 'cos_id' column type to UUID  
    op.execute('ALTER TABLE ce ALTER COLUMN cos_id TYPE UUID USING cos_id::text::uuid')  
  
    # Recreate the foreign key constraint with the updated column types  
    op.create_foreign_key('ce_cos_id_fkey', 'ce', 'cos', ['cos_id'], ['id'])  
  
    # ### end Alembic commands ###  

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    # Note: Downgrading from UUID to INTEGER is not straightforward and may require additional steps
    # to ensure that the INTEGER values are valid (e.g., using a sequence). The following commands are placeholders
    # and should be adjusted according to your application's needs.
    
    # Drop the foreign key constraint before altering the types back
    op.drop_constraint('ce_cos_id_fkey', 'ce', type_='foreignkey')
    
    # Alter the 'cos_id' column on 'ce' table back to INTEGER
    op.execute('ALTER TABLE ce ALTER COLUMN cos_id TYPE INTEGER USING (cos_id::text::integer)')
    
    # Alter the 'id' column on 'cos' table back to INTEGER
    op.execute('ALTER TABLE cos ALTER COLUMN id TYPE INTEGER USING (id::text::integer)')
    
    # Recreate the foreign key constraint with INTEGER type
    op.create_foreign_key('ce_cos_id_fkey', 'ce', 'cos', ['cos_id'], ['id'])
    
    # ### end Alembic commands ###
