"""Added SSPEC project fields

Revision ID: 1d8443402977
Revises: 35c0fb4ccc83
Create Date: 2025-11-20 20:19:29.905648

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1d8443402977'
down_revision = '35c0fb4ccc83'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('domain', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('status', sa.String(length=50), nullable=True))
        batch_op.add_column(sa.Column('owner', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('target_date', sa.Date(), nullable=True))
        batch_op.add_column(sa.Column('integrity_score', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('completion_percentage', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssol', schema=None) as batch_op:
        batch_op.drop_column('completion_percentage')
        batch_op.drop_column('integrity_score')
        batch_op.drop_column('target_date')
        batch_op.drop_column('owner')
        batch_op.drop_column('status')
        batch_op.drop_column('domain')

    # ### end Alembic commands ###
