"""Added CE-Node Attenuation

Revision ID: 4948e08e3637
Revises: 1d8443402977
Create Date: 2025-12-05 21:27:54.624447

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision = '4948e08e3637'
down_revision = '1d8443402977'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssol', schema=None) as batch_op:
        batch_op.add_column(sa.Column('system_data', postgresql.JSONB(astext_type=sa.Text()), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ssol', schema=None) as batch_op:
        batch_op.drop_column('system_data')

    # ### end Alembic commands ###
